-- ============================================================
-- Script 03: Seed de Preguntas ADAPTATIVAS (100 preguntas)
-- ============================================================

TRUNCATE TABLE questions CASCADE;
ALTER SEQUENCE questions_id_seq RESTART WITH 1;

INSERT INTO questions (text, category, specialization_id, min_label, max_label, order_index)
VALUES
('Mi personalidad metódica encaja perfectamente con la tarea de conectar Arduino y sensores.', 'personality', 10, 'Desacuerdo', 'Totalmente', 93),
('Siento un profundo interés por aprender a investigar ataques cibernéticos en el nivel más avanzado.', 'interests', 4, 'Desacuerdo', 'Totalmente', 36),
('Me considero extremadamente hábil para planificar sprints en mi día a día.', 'skills', 7, 'Desacuerdo', 'Totalmente', 65),
('A nivel académico, destaco ampliamente al tener que usar Linux a fondo.', 'academic', 3, 'Desacuerdo', 'Totalmente', 28),
('Me considero extremadamente hábil para atender tickets de servicio en mi día a día.', 'skills', 5, 'Desacuerdo', 'Totalmente', 45),
('A nivel académico, destaco ampliamente al tener que escribir casos de prueba.', 'academic', 6, 'Desacuerdo', 'Totalmente', 54),
('Me considero extremadamente hábil para automatizar despliegues en mi día a día.', 'skills', 3, 'Desacuerdo', 'Totalmente', 25),
('Mi personalidad metódica encaja perfectamente con la tarea de ser meticuloso.', 'personality', 6, 'Desacuerdo', 'Totalmente', 53),
('Siento un profundo interés por aprender a automatizar pruebas en el nivel más avanzado.', 'interests', 6, 'Desacuerdo', 'Totalmente', 52),
('Siento un profundo interés por aprender a revisar flujos críticos en el nivel más avanzado.', 'interests', 6, 'Desacuerdo', 'Totalmente', 60),
('Siento un profundo interés por aprender a usar Python/R en el nivel más avanzado.', 'interests', 2, 'Desacuerdo', 'Totalmente', 16),
('Siento un profundo interés por aprender a trabajar con bases de datos relacionales en el nivel más avanzado.', 'interests', 1, 'Desacuerdo', 'Totalmente', 10),
('Me considero extremadamente hábil para programar en bajo nivel en mi día a día.', 'skills', 10, 'Desacuerdo', 'Totalmente', 91),
('A nivel académico, destaco ampliamente al tener que documentar fallas comunes.', 'academic', 5, 'Desacuerdo', 'Totalmente', 48),
('Siento un profundo interés por aprender a entrenar modelos en el nivel más avanzado.', 'interests', 2, 'Desacuerdo', 'Totalmente', 12),
('Mi personalidad metódica encaja perfectamente con la tarea de entrevistar usuarios.', 'personality', 8, 'Desacuerdo', 'Totalmente', 77),
('Me considero extremadamente hábil para verificar accesibilidad en mi día a día.', 'skills', 6, 'Desacuerdo', 'Totalmente', 59),
('Siento un profundo interés por aprender a monitorear tiempos de actividad en el nivel más avanzado.', 'interests', 3, 'Desacuerdo', 'Totalmente', 26),
('Siento un profundo interés por aprender a orquestar contenedores en el nivel más avanzado.', 'interests', 3, 'Desacuerdo', 'Totalmente', 22),
('A nivel académico, destaco ampliamente al tener que usar Selenium/Cypress.', 'academic', 6, 'Desacuerdo', 'Totalmente', 58),
('Mi personalidad metódica encaja perfectamente con la tarea de escribir código limpio.', 'personality', 1, 'Desacuerdo', 'Totalmente', 3),
('Me considero extremadamente hábil para aplicar estadística en mi día a día.', 'skills', 2, 'Desacuerdo', 'Totalmente', 15),
('A nivel académico, destaco ampliamente al tener que usar Kali Linux.', 'academic', 4, 'Desacuerdo', 'Totalmente', 38),
('Me considero extremadamente hábil para gestionar inventarios digitales en mi día a día.', 'skills', 9, 'Desacuerdo', 'Totalmente', 85),
('Me considero extremadamente hábil para construir APIs en mi día a día.', 'skills', 1, 'Desacuerdo', 'Totalmente', 9),
('Siento un profundo interés por aprender a actuar como hacker ético en el nivel más avanzado.', 'interests', 4, 'Desacuerdo', 'Totalmente', 32),
('Me considero extremadamente hábil para encontrar vulnerabilidades en mi día a día.', 'skills', 4, 'Desacuerdo', 'Totalmente', 31),
('Mi personalidad metódica encaja perfectamente con la tarea de resolver problemas de red locales.', 'personality', 5, 'Desacuerdo', 'Totalmente', 47),
('A nivel académico, destaco ampliamente al tener que crear prototipos interactivos.', 'academic', 8, 'Desacuerdo', 'Totalmente', 78),
('Me considero extremadamente hábil para combinar colores armónicamente en mi día a día.', 'skills', 8, 'Desacuerdo', 'Totalmente', 75),
('Siento un profundo interés por aprender a instalar software de ofimática en el nivel más avanzado.', 'interests', 5, 'Desacuerdo', 'Totalmente', 50),
('Me considero extremadamente hábil para medir el rendimiento de la app en mi día a día.', 'skills', 6, 'Desacuerdo', 'Totalmente', 55),
('A nivel académico, destaco ampliamente al tener que hacer diagramas de Gantt.', 'academic', 7, 'Desacuerdo', 'Totalmente', 68),
('Mi personalidad metódica encaja perfectamente con la tarea de analizar malware.', 'personality', 4, 'Desacuerdo', 'Totalmente', 33),
('Me considero extremadamente hábil para soldar microcontroladores en mi día a día.', 'skills', 10, 'Desacuerdo', 'Totalmente', 99),
('Siento un profundo interés por aprender a mejorar la accesibilidad visual en el nivel más avanzado.', 'interests', 8, 'Desacuerdo', 'Totalmente', 80),
('Me considero extremadamente hábil para ayudar a usuarios en mi día a día.', 'skills', 5, 'Desacuerdo', 'Totalmente', 41),
('Siento un profundo interés por aprender a automatizar contabilidad en el nivel más avanzado.', 'interests', 9, 'Desacuerdo', 'Totalmente', 86),
('Me considero extremadamente hábil para analizar datos en mi día a día.', 'skills', 2, 'Desacuerdo', 'Totalmente', 11),
('Siento un profundo interés por aprender a entender flujos financieros en el nivel más avanzado.', 'interests', 9, 'Desacuerdo', 'Totalmente', 82),
('Siento un profundo interés por aprender a reparar computadoras en el nivel más avanzado.', 'interests', 5, 'Desacuerdo', 'Totalmente', 42),
('Me considero extremadamente hábil para configurar servidores en mi día a día.', 'skills', 3, 'Desacuerdo', 'Totalmente', 21),
('A nivel académico, destaco ampliamente al tener que proteger datos sensibles.', 'academic', 4, 'Desacuerdo', 'Totalmente', 34),
('Me considero extremadamente hábil para parametrizar SAP/Oracle en mi día a día.', 'skills', 9, 'Desacuerdo', 'Totalmente', 81),
('A nivel académico, destaco ampliamente al tener que investigar computación cuántica.', 'academic', 10, 'Desacuerdo', 'Totalmente', 98),
('Mi personalidad metódica encaja perfectamente con la tarea de usar machine learning.', 'personality', 2, 'Desacuerdo', 'Totalmente', 13),
('Mi personalidad metódica encaja perfectamente con la tarea de optimizar recursos humanos.', 'personality', 9, 'Desacuerdo', 'Totalmente', 83),
('Me considero extremadamente hábil para balancear cargas de tráfico en mi día a día.', 'skills', 3, 'Desacuerdo', 'Totalmente', 29),
('Me considero extremadamente hábil para trabajar en Realidad Virtual en mi día a día.', 'skills', 10, 'Desacuerdo', 'Totalmente', 95),
('Siento un profundo interés por aprender a diseñar flujos de navegación en el nivel más avanzado.', 'interests', 8, 'Desacuerdo', 'Totalmente', 76),
('Siento un profundo interés por aprender a entender al usuario final en el nivel más avanzado.', 'interests', 8, 'Desacuerdo', 'Totalmente', 72),
('A nivel académico, destaco ampliamente al tener que usar frameworks modernos.', 'academic', 1, 'Desacuerdo', 'Totalmente', 8),
('Me considero extremadamente hábil para crear wireframes en mi día a día.', 'skills', 8, 'Desacuerdo', 'Totalmente', 71),
('Siento un profundo interés por aprender a estructurar algoritmos en el nivel más avanzado.', 'interests', 1, 'Desacuerdo', 'Totalmente', 6),
('Siento un profundo interés por aprender a procesar lenguaje natural en el nivel más avanzado.', 'interests', 2, 'Desacuerdo', 'Totalmente', 20),
('Mi personalidad metódica encaja perfectamente con la tarea de entender el modelo de negocio.', 'personality', 7, 'Desacuerdo', 'Totalmente', 67),
('Siento un profundo interés por aprender a garantizar la calidad total en el nivel más avanzado.', 'interests', 6, 'Desacuerdo', 'Totalmente', 56),
('Mi personalidad metódica encaja perfectamente con la tarea de romper aplicaciones intencionalmente.', 'personality', 6, 'Desacuerdo', 'Totalmente', 57),
('A nivel académico, destaco ampliamente al tener que mantener redes globales.', 'academic', 3, 'Desacuerdo', 'Totalmente', 24),
('Me considero extremadamente hábil para auditar sistemas en mi día a día.', 'skills', 4, 'Desacuerdo', 'Totalmente', 35),
('Mi personalidad metódica encaja perfectamente con la tarea de diseñar experiencias fluidas.', 'personality', 8, 'Desacuerdo', 'Totalmente', 73),
('Me considero extremadamente hábil para aplicar psicología del diseño en mi día a día.', 'skills', 8, 'Desacuerdo', 'Totalmente', 79),
('Me considero extremadamente hábil para modelar flujos de suministro en mi día a día.', 'skills', 9, 'Desacuerdo', 'Totalmente', 89),
('A nivel académico, destaco ampliamente al tener que limpiar bases de datos grandes.', 'academic', 2, 'Desacuerdo', 'Totalmente', 18),
('Me considero extremadamente hábil para liderar equipos técnicos en mi día a día.', 'skills', 7, 'Desacuerdo', 'Totalmente', 61),
('Siento un profundo interés por aprender a escribir código en C/Rust en el nivel más avanzado.', 'interests', 10, 'Desacuerdo', 'Totalmente', 100),
('Mi personalidad metódica encaja perfectamente con la tarea de crear algoritmos matemáticos puros.', 'personality', 10, 'Desacuerdo', 'Totalmente', 97),
('Mi personalidad metódica encaja perfectamente con la tarea de diagnosticar errores de Windows.', 'personality', 5, 'Desacuerdo', 'Totalmente', 43),
('Siento un profundo interés por aprender a traducir leyes a software en el nivel más avanzado.', 'interests', 9, 'Desacuerdo', 'Totalmente', 90),
('A nivel académico, destaco ampliamente al tener que integrar CRMs.', 'academic', 9, 'Desacuerdo', 'Totalmente', 84),
('Siento un profundo interés por aprender a evitar bloqueos del equipo en el nivel más avanzado.', 'interests', 7, 'Desacuerdo', 'Totalmente', 66),
('A nivel académico, destaco ampliamente al tener que configurar impresoras corporativas.', 'academic', 5, 'Desacuerdo', 'Totalmente', 44),
('Siento un profundo interés por aprender a planificar respuestas a incidentes en el nivel más avanzado.', 'interests', 4, 'Desacuerdo', 'Totalmente', 40),
('Me considero extremadamente hábil para programar redes neuronales en mi día a día.', 'skills', 2, 'Desacuerdo', 'Totalmente', 19),
('A nivel académico, destaco ampliamente al tener que leer papers académicos.', 'academic', 10, 'Desacuerdo', 'Totalmente', 94),
('Me considero extremadamente hábil para actuar con paciencia en mi día a día.', 'skills', 5, 'Desacuerdo', 'Totalmente', 49),
('Mi personalidad metódica encaja perfectamente con la tarea de usar AWS/Azure.', 'personality', 3, 'Desacuerdo', 'Totalmente', 23),
('Siento un profundo interés por aprender a explorar Blockchain en el nivel más avanzado.', 'interests', 10, 'Desacuerdo', 'Totalmente', 92),
('Me considero extremadamente hábil para encontrar bugs en mi día a día.', 'skills', 6, 'Desacuerdo', 'Totalmente', 51),
('A nivel académico, destaco ampliamente al tener que crear aplicaciones web.', 'academic', 1, 'Desacuerdo', 'Totalmente', 4),
('A nivel académico, destaco ampliamente al tener que implementar Salesforce.', 'academic', 9, 'Desacuerdo', 'Totalmente', 88),
('Siento un profundo interés por aprender a usar Scrum o Kanban en el nivel más avanzado.', 'interests', 7, 'Desacuerdo', 'Totalmente', 62),
('A nivel académico, destaco ampliamente al tener que hablar con clientes.', 'academic', 7, 'Desacuerdo', 'Totalmente', 64),
('Me considero extremadamente hábil para programar en mi día a día.', 'skills', 1, 'Desacuerdo', 'Totalmente', 1),
('Mi personalidad metódica encaja perfectamente con la tarea de encriptar información.', 'personality', 4, 'Desacuerdo', 'Totalmente', 37),
('Me considero extremadamente hábil para desarrollar apps móviles en mi día a día.', 'skills', 1, 'Desacuerdo', 'Totalmente', 5),
('Mi personalidad metódica encaja perfectamente con la tarea de visualizar métricas numéricas.', 'personality', 2, 'Desacuerdo', 'Totalmente', 17),
('Siento un profundo interés por aprender a gestionar permisos de red en el nivel más avanzado.', 'interests', 3, 'Desacuerdo', 'Totalmente', 30),
('Mi personalidad metódica encaja perfectamente con la tarea de configurar routers físicos.', 'personality', 3, 'Desacuerdo', 'Totalmente', 27),
('Me considero extremadamente hábil para priorizar tareas en mi día a día.', 'skills', 7, 'Desacuerdo', 'Totalmente', 69),
('Mi personalidad metódica encaja perfectamente con la tarea de auditar procesos de negocio.', 'personality', 9, 'Desacuerdo', 'Totalmente', 87),
('A nivel académico, destaco ampliamente al tener que usar Figma.', 'academic', 8, 'Desacuerdo', 'Totalmente', 74),
('Siento un profundo interés por aprender a mantener inventario de IT en el nivel más avanzado.', 'interests', 5, 'Desacuerdo', 'Totalmente', 46),
('Siento un profundo interés por aprender a optimizar compiladores en el nivel más avanzado.', 'interests', 10, 'Desacuerdo', 'Totalmente', 96),
('Siento un profundo interés por aprender a medir KPIs del producto en el nivel más avanzado.', 'interests', 7, 'Desacuerdo', 'Totalmente', 70),
('Mi personalidad metódica encaja perfectamente con la tarea de definir requerimientos.', 'personality', 7, 'Desacuerdo', 'Totalmente', 63),
('Me considero extremadamente hábil para hacer pruebas de penetración en mi día a día.', 'skills', 4, 'Desacuerdo', 'Totalmente', 39),
('Mi personalidad metódica encaja perfectamente con la tarea de depurar código.', 'personality', 1, 'Desacuerdo', 'Totalmente', 7),
('Siento un profundo interés por aprender a diseñar interfaces en el nivel más avanzado.', 'interests', 1, 'Desacuerdo', 'Totalmente', 2),
('A nivel académico, destaco ampliamente al tener que encontrar patrones en datos.', 'academic', 2, 'Desacuerdo', 'Totalmente', 14);

DO $$ BEGIN RAISE NOTICE '✅ 100 preguntas adaptativas sembradas en revo_db'; END $$;
